//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SICNS.EntityLayer
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SICDBWEBNSEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SICDBWEBNSEntities usando la cadena de conexión encontrada en la sección 'SICDBWEBNSEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SICDBWEBNSEntities() : base("name=SICDBWEBNSEntities", "SICDBWEBNSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SICDBWEBNSEntities.
        /// </summary>
        public SICDBWEBNSEntities(string connectionString) : base(connectionString, "SICDBWEBNSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SICDBWEBNSEntities.
        /// </summary>
        public SICDBWEBNSEntities(EntityConnection connection) : base(connection, "SICDBWEBNSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<SICNS_T_ASISTENCIA> SICNS_T_ASISTENCIA
        {
            get
            {
                if ((_SICNS_T_ASISTENCIA == null))
                {
                    _SICNS_T_ASISTENCIA = base.CreateObjectSet<SICNS_T_ASISTENCIA>("SICNS_T_ASISTENCIA");
                }
                return _SICNS_T_ASISTENCIA;
            }
        }
        private ObjectSet<SICNS_T_ASISTENCIA> _SICNS_T_ASISTENCIA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<SICNS_T_CONTACTO> SICNS_T_CONTACTO
        {
            get
            {
                if ((_SICNS_T_CONTACTO == null))
                {
                    _SICNS_T_CONTACTO = base.CreateObjectSet<SICNS_T_CONTACTO>("SICNS_T_CONTACTO");
                }
                return _SICNS_T_CONTACTO;
            }
        }
        private ObjectSet<SICNS_T_CONTACTO> _SICNS_T_CONTACTO;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet SICNS_T_ASISTENCIA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSICNS_T_ASISTENCIA(SICNS_T_ASISTENCIA sICNS_T_ASISTENCIA)
        {
            base.AddObject("SICNS_T_ASISTENCIA", sICNS_T_ASISTENCIA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet SICNS_T_CONTACTO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSICNS_T_CONTACTO(SICNS_T_CONTACTO sICNS_T_CONTACTO)
        {
            base.AddObject("SICNS_T_CONTACTO", sICNS_T_CONTACTO);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SICDBWEBNSModel", Name="SICNS_T_ASISTENCIA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SICNS_T_ASISTENCIA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto SICNS_T_ASISTENCIA.
        /// </summary>
        /// <param name="colab_c_iid">Valor inicial de la propiedad colab_c_iid.</param>
        public static SICNS_T_ASISTENCIA CreateSICNS_T_ASISTENCIA(global::System.Int32 colab_c_iid)
        {
            SICNS_T_ASISTENCIA sICNS_T_ASISTENCIA = new SICNS_T_ASISTENCIA();
            sICNS_T_ASISTENCIA.colab_c_iid = colab_c_iid;
            return sICNS_T_ASISTENCIA;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 colab_c_iid
        {
            get
            {
                return _colab_c_iid;
            }
            set
            {
                if (_colab_c_iid != value)
                {
                    Oncolab_c_iidChanging(value);
                    ReportPropertyChanging("colab_c_iid");
                    _colab_c_iid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("colab_c_iid");
                    Oncolab_c_iidChanged();
                }
            }
        }
        private global::System.Int32 _colab_c_iid;
        partial void Oncolab_c_iidChanging(global::System.Int32 value);
        partial void Oncolab_c_iidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> asis_c_dfec_ingreso
        {
            get
            {
                return _asis_c_dfec_ingreso;
            }
            set
            {
                Onasis_c_dfec_ingresoChanging(value);
                ReportPropertyChanging("asis_c_dfec_ingreso");
                _asis_c_dfec_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("asis_c_dfec_ingreso");
                Onasis_c_dfec_ingresoChanged();
            }
        }
        private Nullable<global::System.DateTime> _asis_c_dfec_ingreso;
        partial void Onasis_c_dfec_ingresoChanging(Nullable<global::System.DateTime> value);
        partial void Onasis_c_dfec_ingresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> asis_c_dfec_salida
        {
            get
            {
                return _asis_c_dfec_salida;
            }
            set
            {
                Onasis_c_dfec_salidaChanging(value);
                ReportPropertyChanging("asis_c_dfec_salida");
                _asis_c_dfec_salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("asis_c_dfec_salida");
                Onasis_c_dfec_salidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _asis_c_dfec_salida;
        partial void Onasis_c_dfec_salidaChanging(Nullable<global::System.DateTime> value);
        partial void Onasis_c_dfec_salidaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SICDBWEBNSModel", Name="SICNS_T_CONTACTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SICNS_T_CONTACTO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto SICNS_T_CONTACTO.
        /// </summary>
        /// <param name="contac_c_iid">Valor inicial de la propiedad contac_c_iid.</param>
        /// <param name="contac_c_vnombres">Valor inicial de la propiedad contac_c_vnombres.</param>
        /// <param name="contac_c_vape_pater">Valor inicial de la propiedad contac_c_vape_pater.</param>
        /// <param name="contac_c_vape_mater">Valor inicial de la propiedad contac_c_vape_mater.</param>
        /// <param name="contac_c_vcorreo">Valor inicial de la propiedad contac_c_vcorreo.</param>
        public static SICNS_T_CONTACTO CreateSICNS_T_CONTACTO(global::System.Int32 contac_c_iid, global::System.String contac_c_vnombres, global::System.String contac_c_vape_pater, global::System.String contac_c_vape_mater, global::System.String contac_c_vcorreo)
        {
            SICNS_T_CONTACTO sICNS_T_CONTACTO = new SICNS_T_CONTACTO();
            sICNS_T_CONTACTO.contac_c_iid = contac_c_iid;
            sICNS_T_CONTACTO.contac_c_vnombres = contac_c_vnombres;
            sICNS_T_CONTACTO.contac_c_vape_pater = contac_c_vape_pater;
            sICNS_T_CONTACTO.contac_c_vape_mater = contac_c_vape_mater;
            sICNS_T_CONTACTO.contac_c_vcorreo = contac_c_vcorreo;
            return sICNS_T_CONTACTO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 contac_c_iid
        {
            get
            {
                return _contac_c_iid;
            }
            set
            {
                if (_contac_c_iid != value)
                {
                    Oncontac_c_iidChanging(value);
                    ReportPropertyChanging("contac_c_iid");
                    _contac_c_iid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("contac_c_iid");
                    Oncontac_c_iidChanged();
                }
            }
        }
        private global::System.Int32 _contac_c_iid;
        partial void Oncontac_c_iidChanging(global::System.Int32 value);
        partial void Oncontac_c_iidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contac_c_vnombres
        {
            get
            {
                return _contac_c_vnombres;
            }
            set
            {
                Oncontac_c_vnombresChanging(value);
                ReportPropertyChanging("contac_c_vnombres");
                _contac_c_vnombres = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contac_c_vnombres");
                Oncontac_c_vnombresChanged();
            }
        }
        private global::System.String _contac_c_vnombres;
        partial void Oncontac_c_vnombresChanging(global::System.String value);
        partial void Oncontac_c_vnombresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contac_c_vape_pater
        {
            get
            {
                return _contac_c_vape_pater;
            }
            set
            {
                Oncontac_c_vape_paterChanging(value);
                ReportPropertyChanging("contac_c_vape_pater");
                _contac_c_vape_pater = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contac_c_vape_pater");
                Oncontac_c_vape_paterChanged();
            }
        }
        private global::System.String _contac_c_vape_pater;
        partial void Oncontac_c_vape_paterChanging(global::System.String value);
        partial void Oncontac_c_vape_paterChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contac_c_vape_mater
        {
            get
            {
                return _contac_c_vape_mater;
            }
            set
            {
                Oncontac_c_vape_materChanging(value);
                ReportPropertyChanging("contac_c_vape_mater");
                _contac_c_vape_mater = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contac_c_vape_mater");
                Oncontac_c_vape_materChanged();
            }
        }
        private global::System.String _contac_c_vape_mater;
        partial void Oncontac_c_vape_materChanging(global::System.String value);
        partial void Oncontac_c_vape_materChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contac_c_vcorreo
        {
            get
            {
                return _contac_c_vcorreo;
            }
            set
            {
                Oncontac_c_vcorreoChanging(value);
                ReportPropertyChanging("contac_c_vcorreo");
                _contac_c_vcorreo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contac_c_vcorreo");
                Oncontac_c_vcorreoChanged();
            }
        }
        private global::System.String _contac_c_vcorreo;
        partial void Oncontac_c_vcorreoChanging(global::System.String value);
        partial void Oncontac_c_vcorreoChanged();

        #endregion
    
    }

    #endregion
    
}
